// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "ecommerce/features/checkout/domain"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddCheckout provides a mock function with given fields: newHistory, newCheckout
func (_m *Service) AddCheckout(newHistory []domain.HistoryCore, newCheckout domain.Core) (domain.Core, error) {
	ret := _m.Called(newHistory, newCheckout)

	var r0 domain.Core
	if rf, ok := ret.Get(0).(func([]domain.HistoryCore, domain.Core) domain.Core); ok {
		r0 = rf(newHistory, newCheckout)
	} else {
		r0 = ret.Get(0).(domain.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]domain.HistoryCore, domain.Core) error); ok {
		r1 = rf(newHistory, newCheckout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCheckout provides a mock function with given fields: ID
func (_m *Service) DeleteCheckout(ID uint) (domain.Core, error) {
	ret := _m.Called(ID)

	var r0 domain.Core
	if rf, ok := ret.Get(0).(func(uint) domain.Core); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(domain.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCheckout provides a mock function with given fields: id
func (_m *Service) GetCheckout(id uint) ([]domain.Core, error) {
	ret := _m.Called(id)

	var r0 []domain.Core
	if rf, ok := ret.Get(0).(func(uint) []domain.Core); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCheckout provides a mock function with given fields: newCheckout
func (_m *Service) UpdateCheckout(newCheckout domain.Core) {
	_m.Called(newCheckout)
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
